services:

  wordpress:
    container_name: wordpress
    image: wordpress
    restart: always
    expose:
      - "80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: dba
      WORDPRESS_DB_PASSWORD: ${MYSQL_WP_PASS} # must be in .env
      WORDPRESS_DB_NAME: wpdb
      WORDPRESS_SITEURL: https://blog.juissy.net
      WORDPRESS_HOME: https://blog.juissy.net
      VIRTUAL_HOST: blog.juissy.net,alderaan.galaxy.net #LAN only allows 1 DNS name via the ASUS router.
      LETSENCRYPT_HOST: blog.juissy.net
      LETSENCRYPT_EMAIL: admin@juissy.net
    depends_on:
      - db
    volumes:
      - wordpress:/var/www/html
    networks:
      - wordpress_net

  db:
    container_name: wordpress-mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: ${MYSQL_USER}`
      MYSQL_PASSWORD: ${MYSQL_WP_PASS}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
    volumes:
      - db:/var/lib/mysql
    networks:
      - wordpress_net

volumes:
  wordpress:
    name: wordpress_wp_data
  db:
    name: wordpress_db_data

networks:
  wordpress_net:
    external: true